### ISSUE TITLE
remove-luaexec-lafiles removes files from system instead of installation-target

### ISSUE THREAD

**Issue by devurandom** [gvvaughan/slingshot#10]
In my Gentoo ebuild I get a sandbox violation:
```
rm -f /usr/lib/lua/5.1/posix.la
 * ACCESS DENIED:  unlinkat:     /usr/lib/lua/5.1/posix.la
rm: cannot remove ‘/usr/lib/lua/5.1/posix.la’: Permission denied
```

Reason is the `remove-luaexec-lafiles` hook. I would say it is unnecessary – the files do not hurt anyone and removing them, if necessary, is the task of the distribution.

If you want to remove them yourself anyway, then please change `$(luaexecdir)` to `$(DESTDIR)$(luaexecdir)` – you want to operate in the path where the final libraries are going to be installed to, not in the system directory.

**Comment by gvvaughan** [comment]
Nicely caught, thank you!

I don't want to wait for my distro (luarocks over homebrew) to add functionality to clean up noisy file-droppings from the lua module tree, so I've prepended DESTDIR per your second suggestion.  Cheers!
